# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AutoCheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 5 22,13 * * *
    - cron: 35 4 * * *
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3 install requests
        
    - name: AutoCheck
      run: |
        python3 main.py <<EOF
        ${{secrets.STU_NAME}}
        ${{secrets.STU_ID}}
        ${{secrets.DEPT_TEXT}}
        ${{secrets.SC_URL}}
        EOF
